#!/bin/bash
#__Author__: Allen_Jol 2017-11-01
#__Description__: 使用 auto xxx.sh 方式写一个脚本，自动生成头部信息

#判断当文件不存在
if [ ! "$1" ];then
  echo 'Please input an argument as the fileName!'
  exit 1
fi
#判断文件已创建，直接用vim打开
if [ -f "$1" ];then
  vim "$1"
  exit 2
fi

touch "$1"
echo "#!/bin/bash">>"$1"
echo "#__Author__: Allen_Jol">>"$1"
echo "#__Date__: `date +%F' '%H:%M:%S`">>"$1"
vim "$1"
